#BSUB -J SpaRTEn 
#BSUB -P acc_mscic1 
#BSUB -q premium 
#BSUB -n 4
#BSUB -W 6:00 
#BSUB -R rusage[mem=8000]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/mcse/jobs/1.0_mnist-cnn-mcse/logs/%J.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/mcse/jobs/1.0_mnist-cnn-mcse/logs/%J.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1.0_mnist-cnn-mcse

python mnist-cnn-mcse.py