#BSUB -J ptile_cnnMCSE 
#BSUB -P acc_EHR_ML 
#BSUB -q gpu 
#BSUB -n 4
#BSUB -W 48:00 
#BSUB -R rusage[mem=16000]
#BSUB -R rusage[ngpus_excl_p=1]
#BSUB -R span[hosts=1]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.2_cnn-mcse-tl/logs/%J.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.2_cnn-mcse-tl/logs/%J.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
ml cuda
ml cudnn

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.2_cnn-mcse-tl

python cnn-mcse-tl.py --datasets MNIST,FMNIST,KMNIST,QMNIST,EMNIST,CIFAR10,STL10,FAKE \
    --models tlAE,tlFCN \
    --zoo_models alexnet \
    --root_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/data \
    --n_bootstraps 50 --shuffle --batch_size 1 --max_sample_size 5000 \
    --initial_weights_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.2_cnn-mcse-tl/weights \
    --out_data_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.2_cnn-mcse-tl/output/tl_data.tsv \
    --out_metadata_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.2_cnn-mcse-tl/output/tl_metadata.tsv 