
#BSUB -J gpu_cnnMCSE_single_epoch 
#BSUB -P acc_EHR_ML 
#BSUB -q private 
#BSUB -n 4
#BSUB -W 300:00 
#BSUB -R rusage[mem=16000]
#BSUB -R rusage[ngpus_excl_p=1]
#BSUB -R span[hosts=1]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_1/c/logs/%J.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_1/c/logs/%J.stderr 
#BSUB -L /bin/bash 


ml purge
ml python/3.8.2
ml cuda
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_1/c

python figure-1c.py --datasets MNIST,FMNIST,KMNIST,QMNIST,EMNIST,CIFAR10,STL10,FAKE --metric_type sAUC  \
    --models tlAE2,tlFCN2 \
    --zoo_models alexnet \
    --root_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/data  \
    --n_bootstraps 10 --shuffle --batch_size 1 --n_workers 0 --max_sample_size 500 --frequency --stratified \
    --n_epochs 1 \
    --absolute_scale 16 \
    --initial_weights_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_1/c/weights \
    --out_data_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/output/figure1/c/data_epoch_10_small.tsv \
    --out_metadata_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/output/figure1/c/metadata_epoch_10_small.tsv 