#BSUB -J ptile_cnnMCSE 
#BSUB -P acc_mscic1 
#BSUB -q premium 
#BSUB -n 8
#BSUB -W 6:00 
#BSUB -R rusage[mem=16000]
#BSUB -R span[ptile=4]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.0_cnn-mcse-fcns/logs/%J.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.0_cnn-mcse-fcns/logs/%J.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.0_cnn-mcse-fcns

python cnn-mcse-fcns.py --datasets MNIST,FMNIST \
    --models A3,FCN \
    --root_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/data \
    --n_bootstraps 1 --shuffle --batch_size 1 --num_workers 0 --max_sample_size 1000 \
    --initial_weights_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.0_cnn-mcse-fcns/weights \
    --out_data_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.0_cnn-mcse-fcns/output/fcn_data.tsv \
    --out_metadata_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.0_cnn-mcse-fcns/output/fcn_metadata.tsv 