#BSUB -J ptile_cnnMCSE_MIMIC_ethnicity
#BSUB -P acc_mscic1 
#BSUB -q premium 
#BSUB -n 8
#BSUB -W 48:00 
#BSUB -R rusage[mem=16000]
#BSUB -R span[ptile=4]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/4_cnn-mcse-mimic/4.3_mimic-medicare/logs/%J.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/4_cnn-mcse-mimic/4.3_mimic-medicare/logs/%J.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/4_cnn-mcse-mimic/4.3_mimic-medicare

python mimic-medicare.py --datasets medicare --metric_type sAUC --models A3,FCN --experiment MIMIC \
    --root_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/4_cnn-mcse-mimic/4.3_mimic-medicare/data  \
    --n_bootstraps 1 --shuffle --batch_size 1 --n_workers 0 --max_sample_size 1000 --frequency --stratified \
    --initial_weights_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/4_cnn-mcse-mimic/4.3_mimic-medicare/weights \
    --out_data_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/4_cnn-mcse-mimic/4.3_mimic-medicare/data/data.tsv \
    --out_metadata_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/4_cnn-mcse-mimic/4.3_mimic-medicare/data/fcn_metadata.tsv