initial_weights_dir: /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/12_sota-update/12.1_sota-update/weights
estimand: tlRADFCN
dataset_list: ['ethnicity']
experiment: "MIMIC"
root_dir: '/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/data'
using_pretrained: True
batch_size: 64
num_workers: 48
zoo_model: "radimagenet"
max_epochs: 30
num_classes: 10
checkpoint_path: "/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/12_sota-update/12.4_sota-lightning/checkpoint_path"
save_dir: "/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/12_sota-update/12.4_sota-lightning/lightning_logs"
auto_lr_find: True
num_gpus: 1
num_nodes: 1
refresh_rate: 20
accelerator: "ddp"
auto_scale_batch_size: True
checkpoint_interval: 10000
gradient_clip_val: 1.0
seed: 42
output_directory: '/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/12_sota-update/12.4_sota-lightning/data'