
#BSUB -J "MIMIC_TL_batch_ses[1-50]"
#BSUB -P acc_EHR_ML 
#BSUB -q private
#BSUB -n 4
#BSUB -W 144:00 
#BSUB -R rusage[mem=16000]
#BSUB -R rusage[ngpus_excl_p=1]
#BSUB -R span[hosts=1]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/10_intersectional-biases/10.3_intersectional-ses/10.3.1_medicaid-private/logs/%J.%I.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/10_intersectional-biases/10.3_intersectional-ses/10.3.1_medicaid-private/logs/%J.%I.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/10_intersectional-biases/10.3_intersectional-ses/10.3.1_medicaid-private

echo "$LSB_JOBINDEX"
export CURRENT_BOOTSTRAP="$LSB_JOBINDEX"
echo "%I"


python medicaid-private.py --datasets ses --metric_type sAUC --experiment MIMIC \
    --models tlAE2,tlFCN2 \
    --zoo_models alexnet \
    --root_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/data  \
    --n_bootstraps 1 --shuffle --batch_size 1 --n_workers 0 --max_sample_size 50000 --frequency --stratified  --start_seed "$LSB_JOBINDEX" \
    --initial_weights_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_3/a/weights \
    --out_data_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/10_intersectional-biases/10.3_intersectional-ses/10.3.1_medicaid-private/data/tl_data_v2_"$LSB_JOBINDEX".tsv \
    --out_metadata_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/10_intersectional-biases/10.3_intersectional-ses/10.3.1_medicaid-private/data/tl_metadata_v2_"$LSB_JOBINDEX".tsv \
    --out_prediction_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/10_intersectional-biases/10.3_intersectional-ses/10.3.1_medicaid-private/data/tl_predictions_"$LSB_JOBINDEX".tsv \

