
#BSUB -J MIMIC_experiment 
#BSUB -P acc_EHR_ML 
#BSUB -q gpu 
#BSUB -n 4
#BSUB -W 144:00 
#BSUB -R rusage[mem=16000]
#BSUB -R rusage[ngpus_excl_p=1]
#BSUB -R span[hosts=1]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_3/a/logs/%J.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_3/a/logs/%J.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_3/a

python figure-3a.py --datasets test --metric_type sAUC --models A3,FCN --experiment MIMIC \
    --root_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/data  \
    --n_bootstraps 1 --shuffle --batch_size 1 --n_workers 0 --max_sample_size 500 --frequency --stratified \
    --initial_weights_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_3/a/weights \
    --out_data_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/output/figure3/a/fcn_data.tsv \
    --out_metadata_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/output/figure3/a/fcn_metadata.tsv

