#BSUB -J ptile_cnnMCSE 
#BSUB -P acc_mscic1 
#BSUB -q premium 
#BSUB -n 8
#BSUB -W 48:00 
#BSUB -R rusage[mem=16000]
#BSUB -R span[ptile=4]
#BSUB -oo /mnt/c/Users/faris/Documents/sinai/Research/Nadkarni/cnnMCSE/jobs/2_cnn-smcse-experiments/logs/%J.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/2_cnn-smcse-experiments/2.1_cnn-smcse-sAUC/logs/%J.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/1_cnn-mcse-baselines/1.0_cnn-mcse-fcns

python cnn-mcse-label-bias.py --datasets MNIST --metric_type sAUC --models A3,FCN --experiment label \
    --root_dir /mnt/c/Users/faris/Documents/sinai/Research/Nadkarni/cnnMCSE/data  \
    --n_bootstraps 1 --shuffle --batch_size 1 --n_workers 0 --max_sample_size 500 --frequency --stratified \
    --initial_weights_dir /mnt/c/Users/faris/Documents/sinai/Research/Nadkarni/cnnMCSE/jobs/3_cnn-mcse-bias/3.3_cnn-mcse-label-bias/weights \
    --out_data_path /mnt/c/Users/faris/Documents/sinai/Research/Nadkarni/cnnMCSE/jobs/3_cnn-mcse-bias/3.3_cnn-mcse-label-bias/data/data.tsv \
    --out_metadata_path /mnt/c/Users/faris/Documents/sinai/Research/Nadkarni/cnnMCSE/jobs/3_cnn-mcse-bias/3.3_cnn-mcse-label-bias/data/fcn_metadata.tsv


python cnn-mcse-label-bias.py --datasets MNIST --metric_type sAUC --models A3,FCN --experiment label --root_dir /mnt/c/Users/faris/Documents/sinai/Research/Nadkarni/cnnMCSE/data --n_bootstraps 1 --shuffle --batch_size 1 --n_workers 0 --max_sample_size 500 --frequency --stratified --initial_weights_dir /mnt/c/Users/faris/Documents/sinai/Research/Nadkarni/cnnMCSE/jobs/3_cnn-mcse-bias/3.3_cnn-mcse-label-bias/weights --out_data_path /mnt/c/Users/faris/Documents/sinai/Research/Nadkarni/cnnMCSE/jobs/3_cnn-mcse-bias/3.3_cnn-mcse-label-bias/data/data.tsv  --out_metadata_path /mnt/c/Users/faris/Documents/sinai/Research/Nadkarni/cnnMCSE/jobs/3_cnn-mcse-bias/3.3_cnn-mcse-label-bias/data/fcn_metadata.tsv