#BSUB -J MIMIC_TL_Merge
#BSUB -P acc_EHR_ML 
#BSUB -q premium 
#BSUB -n 3
#BSUB -W 4:00 
#BSUB -R rusage[mem=16000]
#BSUB -R span[hosts=1]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_5/d/batch_logs/%J.%I.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_5/d/batch_logs/%J.%I.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_5/d

python figure-5d-merge.py --input_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_5/d/data --output_file /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/output/figure5/d/tl_data_50.tsv