#BSUB -J "MIMIC_TL_SOTA_V3[1-3]"
#BSUB -P acc_EHR_ML 
#BSUB -q gngpu
#BSUB -n 1
#BSUB -W 140:00 
#BSUB -R rusage[mem=64000]
#BSUB -R affinity[core(8)]
#BSUB -gpu num=1
#BSUB -R a100 
#BSUB -R span[hosts=1]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/12_sota-update/12.1_sota-update/logs/%J.%I.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/12_sota-update/12.1_sota-update/logs/%J.%I.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/12_sota-update/12.1_sota-update
echo "$LSB_JOBINDEX"
export CURRENT_BOOTSTRAP="$LSB_JOBINDEX"
echo "%I"


python sota-update.py --datasets ethnicity --metric_type sAUC --experiment MIMIC \
    --models tlRADA3,tlRADFCN \
    --zoo_models radimagenet \
    --root_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/data  \
    --n_bootstraps 1 --shuffle --batch_size 1 --n_workers 1 --max_sample_size 50000 --min_sample_size 30000\
    --frequency --stratified  --start_seed "$LSB_JOBINDEX" \
    --initial_weights_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_3/a/weights \
    --out_data_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/12_sota-update/12.1_sota-update/data/tl_data_v2_"$LSB_JOBINDEX".tsv \
    --out_metadata_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/12_sota-update/12.1_sota-update/data/tl_metadata_v2_"$LSB_JOBINDEX".tsv \
    --out_prediction_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/12_sota-update/12.1_sota-update/data/tl_predictions_"$LSB_JOBINDEX".tsv \


