
#BSUB -J sampling_experiment_TL_ratios_50K_50E_private
#BSUB -P acc_EHR_ML 
#BSUB -q private 
#BSUB -n 4
#BSUB -W 300:00 
#BSUB -R rusage[mem=16000]
#BSUB -R rusage[ngpus_excl_p=1]
#BSUB -R span[hosts=1]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_2/a/tl_logs/%J.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_2/a/tl_logs/%J.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_2/a

python figure-2a.py --datasets MNIST_ratios --metric_type sAUC --experiment sampling \
    --models tlAE2,tlFCN2 \
    --zoo_models alexnet \
    --root_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/data  \
    --n_bootstraps 50 --shuffle --batch_size 1 --n_workers 0 --max_sample_size 50000 --frequency --stratified \
    --initial_weights_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/Figures/figure_2/a/weights \
    --out_data_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/output/figure2/a/tl_data_ratios_50E_50K_V2.tsv \
    --out_metadata_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/output/figure2/a/tl_metadata_ratios_50E_50K_V2.tsv

