#BSUB -J gpu_cnnMCSE 
#BSUB -P acc_EHR_ML 
#BSUB -q gpu 
#BSUB -n 4
#BSUB -W 48:00 
#BSUB -R rusage[mem=16000]
#BSUB -R rusage[ngpus_excl_p=1]
#BSUB -R span[hosts=1]
#BSUB -oo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/figure_1/a/logs/%J.stdout 
#BSUB -eo /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/figure_1/a/logs/%J.stderr 
#BSUB -L /bin/bash 

ml purge
ml python/3.8.2
echo $PYTHONPATH
export PYTHONPATH=/hpc/packages/minerva-centos7/python/3.8.2/lib/python3.8/site-packages:/sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv/lib/python3.8/site-packages

cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/mcse-venv
source bin/activate
cd /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/figure_1/a

python figure-1a.py --datasets MNIST --metric_type sAUC --models A3,FCN \
    --root_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/data  \
    --n_bootstraps 50 --shuffle --batch_size 1 --n_workers 0 --max_sample_size 5000 --frequency --stratified \
    --initial_weights_dir /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/jobs/figure_1/a/weights \
    --out_data_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/output/figure1/a/fcn_data_50.tsv \
    --out_metadata_path /sc/arion/projects/EHR_ML/gulamf01/cnnMCSE/output/figure1/a/fcn_metadata_50.tsv 